---
app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.8
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: home.epx.pub
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - home.epx.pub
          secretName: homepage-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: >
          title: EPX Home

          background:
          https://images.squarespace-cdn.com/content/v1/673776e8f55fd72f60813df1/bcd3d37f-3a4b-482a-8fc8-c197aece48c2/sil29.jpg?format=2500w

          cardBlur: md

          theme: dark

          headerStyle: boxed

          hideVersion: true

          favicon: https://search.epx.pub/static/themes/simple/img/favicon.png
        widgets.yaml: |
          - search:
              provider: custom
              url: https://search.epx.pub/search?q=
              focus: true
              target: _blank
        services.yaml: |
          - Popular:
            - Matrix:
                href: https://chat.epx.pub
                description: Chat client
                icon: element.svg
            - Jellyfin:
                href: https://jellyfin.epx.pub
                description: Media system (movies, music, etc.)
                icon: jellyfin.svg
            - Jellyseerr:
                href: https://jellyseerr.epx.pub
                description: Request media
                icon: jellyseerr.svg
            - Paperless:
                href: https://paperless.epx.pub
                description: Document management system
                icon: paperless.svg
            - Vaultwarden:
                href: https://sec.epx.pub
                description: Secret management system
                icon: vaultwarden.svg
          - Management:
            - Transmission:
                href: https://transmission.epx.pub
                description: Bittorrent client
                icon: transmission.svg
            - Prowlarr:
                href: https://prowlarr.epx.pub
                description: Indexer manager
                icon: prowlarr.svg
            - Radarr:
                href: https://radarr.epx.pub
                description: Movie manager
                icon: radarr.svg
            - Sonarr:
                href: https://sonarr.epx.pub
                description: TV show manager
                icon: sonarr.svg
            - Kanidm:
                href: https://auth.epx.pub
                description: Identity management
                icon: https://auth.epx.pub/pkg/img/logo-square.svg
          - Development:
            - Gitea:
                href: https://git.epx.pub
                description: Git forge
                icon: gitea.svg
            - Woodpecker:
                href: https://ci.epx.pub
                description: Continuous integration
                icon: woodpecker-ci.svg
            - ArgoCD:
                href: https://argocd.epx.pub
                description: Continuous deployment
                icon: argo-cd.svg
            - Registry:
                href: https://registry.epx.pub
                description: Container registry
                icon: docker.svg
            - Grafana:
                href: https://grafana.epx.pub
                description: Observability dashboards
                icon: grafana.svg
          - Utilities:
            - Excalidraw:
                href: https://draw.epx.pub
                description: Virtual whiteboard
                icon: excalidraw.svg
            - Speedtest:
                href: https://speedtest.epx.pub
                description: Internal network speed test
                icon: openspeedtest.png
        bookmarks.yaml: |
          - Homelab:
            - Documentation (broken):
              - href: https://homelab.epx.pub
                icon: google-docs.svg
            - NordWest homelab repository:
              - href: https://git.epx.pub/NordWest/homelab/
                icon: gitea.svg
            - Public homelab repository:
              - href: https://github.com/khuedoan/homelab
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
            - Zero Trust:
              - href: https://one.dash.cloudflare.com
                icon: cloudflare-zero-trust.svg
            - Terraform Cloud:
              - href: https://app.terraform.io
                icon: terraform.svg
          - Infrastructure:
            - Unifi Cloud:
              - href: https://192.168.1.8
                icon: router.svg
            - UPS:
              - href: https://192.168.1.35
                icon: ups.svg
            - Cisco Flur:
              - href: https://192.168.1.6/cs50672d0a
                icon: cisco.svg
            - Cisco Office:
              - href: https://192.168.1.32/cs55ffa354
                icon: cisco.svg
            - LowerBlade Office:
              - href: https://192.168.1.24:9090
                icon: ubuntu-linux.svg
            - LowerBlade Office S3:
              - href: http://192.168.1.24:9001
                icon: minio.svg
            - TrueNAS (future UpperBlade Office):
              - href: https://192.168.1.23:444
                icon: truenas-scale.svg
