app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/vaultwarden/server
            tag: 1.30.1
          env:
            WEBSOCKET_ENABLED: "true"
            SIGNUPS_ALLOWED: "false"
            # Disable admin page by default for security
            # To enable temporarily, set ADMIN_TOKEN in the Secret
            ADMIN_TOKEN:
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: ADMIN_TOKEN
  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP
        websocket:
          port: 3012
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host sec.epx.pub
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
            - path: /notifications/hub
              pathType: Prefix
              service:
                name: main
                port: websocket
            - path: /notifications/hub/negotiate
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: vaultwarden-tls-certificate
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /data
