apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: spliit-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  # Storage configuration
  storage:
    size: 1Gi
    storageClass: standard-rwo

  # Database configuration
  bootstrap:
    initdb:
      database: spliit
      owner: spliit
      secret:
        name: spliit-database-credentials

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spliit-database-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        username: spliit
        password: {{ `"{{ .password }}"` }}
  data:
    - secretKey: password
      remoteRef:
        key: spliit.database
        property: password
