apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spliit-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        AUTH_SECRET: {{ `"{{ .auth_secret }}"` }}
        COOKIE_SECRET: {{ `"{{ .cookie_secret }}"` }}
        DATABASE_URL: {{ `"postgresql://spliit:{{ .db_password }}@spliit-postgresql:5432/spliit"` }}
  data:
    - secretKey: auth_secret
      remoteRef:
        key: spliit.auth
        property: auth_secret
    - secretKey: cookie_secret
      remoteRef:
        key: spliit.auth
        property: cookie_secret
    - secretKey: db_password
      remoteRef:
        key: spliit.database
        property: password
