# TODO create user and access token
# users:
#   - name: renovate
#     fullName: Renovate
#     email: info+1@epx.pub
#     tokenSecretRef: renovate-secret
organizations:
  - name: ops
    description: Operations
    teams:
      - name: Owners
        members:
          - renovate
repositories:
  - name: homelab
    owner: ops
    private: false
    migrate:
      source: https://github.com/Enraged-Pixels/homelab
      mirror: false
