apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: vaultwarden.admin
        property: token
