apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate_secret_gitea
  namespace: renovate
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        key: external
        property: renovate_secret_gitea
      secretKey: renovate_secret_gitea
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: "{{ .renovate_secret_gitea }}"
