apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-secret
  namespace: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: renovate
  target:
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: {{` "{{ .RENOVATE_TOKEN }}" `}}
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovate-secret
        property: RENOVATE_TOKEN
