apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.renovate.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        key: external
        property: renovate-secret-gitea
      secretKey: renovate-secret-gitea
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: {{` "{{ .renovate-secret-gitea }}" `}}
