apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-secret-gitea
  namespace: renovate
spec:
  data:
    - remoteRef:
        key: external
        property: renovate-secret-gitea
      secretKey: renovate_secret_gitea
    - remoteRef:
        key: external
        property: renovate-github-token
      secretKey: renovate_github_token
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        RENOVATE_GITHUB_COM_TOKEN: {{` "{{ .renovate_github_token }}" `}}
        RENOVATE_TOKEN: {{` "{{ .renovate_secret_gitea }}" `}}
