app-template:
  controllers:
    main:
      initContainers:
        init-repo:
          image:
            repository: alpine/git
            tag: 2.40.1
          command:
            - /bin/sh
            - -c
          args:
            - |
              git clone https://github.com/spliit-app/spliit.git /app-src
          volumeMounts:
            - name: app-src
              mountPath: /app-src
      containers:
        main:
          image:
            repository: node
            tag: 18-alpine
          command:
            - /bin/sh
            - -c
          args:
            - |
              cd /app-src &&
              npm ci &&
              npm run build &&
              npm start
          env:
            # For authentication with the Spliit service
            AUTH_SECRET:
              valueFrom:
                secretKeyRef:
                  name: spliit-secret
                  key: AUTH_SECRET
            # Used for cookie signing
            COOKIE_SECRET:
              valueFrom:
                secretKeyRef:
                  name: spliit-secret
                  key: COOKIE_SECRET
            # Database credentials
            DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: spliit-secret
                  key: DATABASE_URL
            # Set Node environment
            NODE_ENV: production
            PORT: "3000"
          volumeMounts:
            - name: app-src
              mountPath: /app-src
  persistence:
    app-src:
      enabled: true
      type: emptyDir
      medium: Memory
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /app-src/data
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host spliit.epx.pub
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: spliit-tls-certificate
