app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/spliit-app/spliit
            tag: latest
  service:
    main:
      ports:
        http:
          port: 5000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host spliit.epx.pub
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: spliit-tls-certificate
  persistence:
    data:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /data
