app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/spliit-app/spliit
            tag: 1.15.0
          env:
            # For authentication with the Spliit service
            AUTH_SECRET:
              valueFrom:
                secretKeyRef:
                  name: spliit-secret
                  key: AUTH_SECRET
            # Used for cookie signing
            COOKIE_SECRET:
              valueFrom:
                secretKeyRef:
                  name: spliit-secret
                  key: COOKIE_SECRET
            # Database credentials
            DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: spliit-secret
                  key: DATABASE_URL
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host split.epx.pub
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: spliit-tls-certificate
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /app/data
