all:
  vars:
    control_plane_endpoint: 192.168.1.3
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.50, mac: '00:15:5d:b2:15:06', disk: sda, network_interface: eth0}
        metal1: {ansible_host: 192.168.1.51, mac: '00:15:5d:b2:15:07', disk: sda, network_interface: eth0}
        metal2: {ansible_host: 192.168.1.52, mac: '00:15:5d:b2:15:08', disk: sda, network_interface: eth0}
