all:
  vars:
    control_plane_endpoint: 192.168.1.3
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        laptop-master1:
          {
            ansible_host: 192.168.1.63,
            mac: "00:15:5d:b2:15:0c",
            disk: sda,
            network_interface: eth0,
          }
        laptop-master2:
          {
            ansible_host: 192.168.1.64,
            mac: "00:15:5d:b2:15:0d",
            disk: sda,
            network_interface: eth0,
          }
        laptop-master3:
          {
            ansible_host: 192.168.1.55,
            mac: "00:15:5d:b2:15:11",
            disk: sda,
            network_interface: eth0,
          }
        tower-master1:
          {
            ansible_host: 192.168.1.77,
            mac: "00:15:5d:01:36:01",
            disk: sda,
            network_interface: eth0,
          }
        tower-master2:
          {
            ansible_host: 192.168.1.78,
            mac: "00:15:5d:01:36:02",
            disk: sda,
            network_interface: eth0,
          }
        pi-master1:
          {
            ansible_host: 192.168.1.56,
            mac: "b8:27:eb:24:68:3e",
            disk: sda,
            network_interface: eth0,
          }
        # lowerblade-master1:
        #   {
        #     ansible_host: 192.168.1.73,
        #     mac: "52:54:00:ab:c6:21",
        #     disk: vda,
        #     network_interface: net0,
        #   }

    workers:
      hosts:
        laptop-worker1:
          {
            ansible_host: 192.168.1.120,
            mac: "00:15:5d:b2:15:0e",
            disk: sda,
            network_interface: eth0,
          }
        laptop-worker2:
          {
            ansible_host: 192.168.1.121,
            mac: "00:15:5d:b2:15:0f",
            disk: sda,
            network_interface: eth0,
          }
        laptop-worker3:
          {
            ansible_host: 192.168.1.122,
            mac: "00:15:5d:b2:15:10",
            disk: sda,
            network_interface: eth0,
          }
