all:
  vars:
    control_plane_endpoint: 192.168.1.3
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        laptop-master1:
          {
            ansible_host: 192.168.1.110,
            mac: "00:23:24:d1:f5:69",
            disk: sda,
            network_interface: eth0,
          }
        laptop-master2:
          {
            ansible_host: 192.168.1.111,
            mac: "00:23:24:d1:f3:f0",
            disk: sda,
            network_interface: eth0,
          }
        tower-master1:
          {
            ansible_host: 192.168.1.112,
            mac: "00:23:24:e7:04:60",
            disk: sda,
            network_interface: eth0,
          }
      workers:
        hosts:
          laptop-worker1:
            {
              ansible_host: 192.168.1.120,
              mac: "00:23:24:d1:f4:d6",
              disk: sda,
              network_interface: eth0,
            }
          laptop-worker2:
            {
              ansible_host: 192.168.1.121,
              mac: "00:23:24:d1:f4:d6",
              disk: sda,
              network_interface: eth0,
            }
          laptop-worker3:
            {
              ansible_host: 192.168.1.122,
              mac: "00:23:24:d1:f4:d6",
              disk: sda,
              network_interface: eth0,
            }
