renovate:
  cronjob:
    schedule: "0 9 * * *" # Everyday at 09:00
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://git.epx.pub/api/v1",
        "gitAuthor": "EPX Renovate",
        "autodiscover": true
      }
  existingSecret: renovate_secret_gitea
