renovate:
  cronjob:
    schedule: "0 9 * * *" # Everyday at 09:00
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://git.epx.pub/api/v1",
        "gitAuthor": "EPX Renovate <renovate@epx.pub>",
        "autodiscover": true,
        "hostRules": [
                  {
                    "hostType": "github",
                    "matchHost": "github.com",
                    "token": "${GITHUB_COM_TOKEN}"
                  }
      }
  existingSecret: renovate-secret-gitea
