app-template:
  controllers:
    server:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: "v1.99.0"
          env:
            DB_HOSTNAME: "{{ .Release.Name }}-postgresql"
            DB_DATABASE_NAME: "immich"
            DB_USERNAME: "immich"
            DB_PORT: "5432"
            REDIS_HOSTNAME: "{{ .Release.Name }}-redis"
            REDIS_PORT: "6379"
            IMMICH_MACHINE_LEARNING_URL: "http://{{ .Release.Name }}-machine-learning:3003"
            IMMICH_MICROSERVICES_URL: "http://{{ .Release.Name }}-microservices:3002"
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 250Mi

    microservices:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: "v1.99.0"
          args:
            - "microservices"
          env:
            DB_HOSTNAME: "{{ .Release.Name }}-postgresql"
            DB_DATABASE_NAME: "immich"
            DB_USERNAME: "immich"
            DB_PORT: "5432"
            REDIS_HOSTNAME: "{{ .Release.Name }}-redis"
            REDIS_PORT: "6379"
            IMMICH_MACHINE_LEARNING_URL: "http://{{ .Release.Name }}-machine-learning:3003"
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 250Mi

    machine-learning:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            tag: "v1.99.0"
          env:
            CPU_WORKER_COUNT: "2"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi

    web:
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-web
            tag: "v1.99.0"
          env:
            IMMICH_SERVER_URL: "http://{{ .Release.Name }}-server:3001"
          resources:
            requests:
              cpu: 100m
              memory: 250Mi

    redis:
      containers:
        main:
          image:
            repository: redis
            tag: "7.2.4-alpine"
          resources:
            requests:
              cpu: 100m
              memory: 250Mi

    postgresql:
      containers:
        main:
          image:
            repository: postgres
            tag: "15.5-alpine"
          env:
            POSTGRES_USER: "immich"
            POSTGRES_DB: "immich"
            PGDATA: "/var/lib/postgresql/data/pgdata"
            POSTGRES_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: 200m
              memory: 512Mi

  service:
    server:
      controller: server
      ports:
        http:
          port: 3001

    microservices:
      controller: microservices
      ports:
        http:
          port: 3002

    machine-learning:
      controller: machine-learning
      ports:
        http:
          port: 3003

    web:
      controller: web
      ports:
        http:
          port: 3000

    redis:
      controller: redis
      ports:
        redis:
          port: 6379

    postgresql:
      controller: postgresql
      ports:
        postgresql:
          port: 5432

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: &host photos.epx.pub
          paths:
            - path: /api
              pathType: Prefix
              service:
                name: server
                port: http
            - path: /
              pathType: Prefix
              service:
                name: web
                port: http
      tls:
        - hosts:
            - *host
          secretName: immich-tls-certificate

  persistence:
    library:
      enabled: true
      storageClass: zfs-nfs
      accessMode: ReadWriteMany
      size: 100Gi
      globalMounts:
        - path: /usr/src/app/upload

    postgres-data:
      enabled: true
      storageClass: zfs-nfs
      accessMode: ReadWriteMany
      size: 20Gi
      advancedMounts:
        postgresql:
          main:
            - path: /var/lib/postgresql/data

    redis-data:
      enabled: true
      storageClass: zfs-nfs
      accessMode: ReadWriteMany
      size: 2Gi
      advancedMounts:
        redis:
          main:
            - path: /data

  # External secret for PostgreSQL password
  rawResources:
    secret:
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: immich-secret
      spec:
        secretStoreRef:
          kind: ClusterSecretStore
          name: global-secrets
        data:
          - secretKey: POSTGRES_PASSWORD
            remoteRef:
              key: immich.postgres
              property: password
