app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
  controllers:
    main:
      containers:
        server:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: v1.99.0
          env:
            DB_DATABASE_NAME: immich
            DB_HOSTNAME: immich-postgresql
            DB_PORT: 5432
            DB_USERNAME: immich
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: POSTGRES_PASSWORD
            REDIS_HOSTNAME: immich-redis
            REDIS_PORT: 6379
            IMMICH_MACHINE_LEARNING_URL: http://localhost:3003
            IMMICH_MICROSERVICES_URL: http://localhost:3002
        microservices:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: v1.99.0
          args:
            - microservices
          env:
            DB_DATABASE_NAME: immich
            DB_HOSTNAME: immich-postgresql
            DB_PORT: 5432
            DB_USERNAME: immich
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-secret
                  key: POSTGRES_PASSWORD
            REDIS_HOSTNAME: immich-redis
            REDIS_PORT: 6379
            IMMICH_MACHINE_LEARNING_URL: http://localhost:3003
        machine-learning:
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            tag: v1.99.0
          env:
            CPU_WORKER_COUNT: "2"
        web:
          image:
            repository: ghcr.io/immich-app/immich-web
            tag: v1.99.0
        redis:
          image:
            repository: redis
            tag: 7.2.4-alpine
        postgres:
          image:
            repository: postgres
            tag: 15.5-alpine
          env:
            POSTGRES_USER: immich
            POSTGRES_DB: immich
            POSTGRES_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich.secret
                  key: POSTGRES_PASSWORD
            PGDATA: /var/lib/postgresql/data/pgdata
  service:
    main:
      ports:
        http:
          port: 3001
          protocol: HTTP
        microservices:
          port: 3002
          protocol: HTTP
        ml:
          port: 3003
          protocol: HTTP
        postgres:
          port: 5432
          protocol: TCP
        redis:
          port: 6379
          protocol: TCP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host photos.epx.pub
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: immich-tls-certificate
  persistence:
    data:
      enabled: true
      storageClass: zfs-nfs
      accessMode: ReadWriteMany
      size: 100Gi
      advancedMounts:
        main:
          server:
            - path: /usr/src/app/upload
              subPath: immich/upload
          microservices:
            - path: /usr/src/app/upload
              subPath: immich/upload
          postgres:
            - path: /var/lib/postgresql/data
              subPath: immich/pgdata
    tmp:
      enabled: true
      type: emptyDir
      advancedMounts:
        main:
          machine-learning:
            - path: /tmp
