# Gitea
- name: gitea.admin
  data:
    - key: password
      length: 32
      special: true

# Dex
- name: dex.grafana
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.gitea
  data:
    - key: client_secret
      length: 32
      special: false

# Registry
- name: registry.admin
  data:
    - key: password
      length: 32
      special: true

# Woodpecker
- name: woodpecker.agent
  data:
    - key: secret
      length: 32
      special: false

# Paperless
- name: paperless.admin
  data:
    - key: PAPERLESS_ADMIN_PASSWORD
      length: 32
      special: true

# Vaultwarden
- name: vaultwarden.admin
  data:
    - key: token
      length: 64
      special: true

# Spliit
- name: spliit.auth
  data:
    - key: auth_secret
      length: 64
      special: false
    - key: cookie_secret
      length: 64
      special: false
- name: spliit.database
  data:
    - key: password
      length: 32
      special: true
